version: '3'

services:

  velocity_converter:
    build:
      context: $ROOT_DIR/
      dockerfile: $ROOT_DIR/Dockerfile
    image: velocity_converter:latest
    environment:
      - INPUT_TOPIC=$INPUT_TOPIC
      - WHEEL_DISTNCE=$WHEEL_DISTNCE
      - MAX_WHEEL_SPEED=$MAX_WHEEL_SPEED
    network_mode: host
    command: ros2 launch velocity_converter velocity_converter.launch.py